### ISSUE TITLE
example code shoud contain toBeRedirectToSignedRoute() instead toBeRedirect

### ISSUE THREAD

**Issue by dr41d45** [defstudio/pest-plugin-laravel-expectations#106]
example code shoud contain `toBeRedirectToSignedRoute() `instead `toBeRedirect` in line 59

https://github.com/defstudio/pest-plugin-laravel-expectations/blob/3ba924552109979af9dfc7b3a3d7e3e2035ecc97/docs/content/en/expectations/responses.md?plain=1#L54-L59

**Comment by fabio-ivona** [comment]
thanks for pointing this out!

**Comment by fabio-ivona** [comment]
fixed, thanks!

**Comment by fabio-ivona** [comment]
Fixed, thanks!
